### ISSUE TITLE
Feature Request - Module for Issues

### ISSUE THREAD

**Issue by TGoodrich** [itsam/imc#13]
The website i would like to use IMC3 on is a Gantry based template and currently I can not use IMC3 as it is unless i include alot of custom css. Currently you offer a filter and map module which is great but it would be even better with an issue's module if that is possible. This way we would have more control over layout. I really like your full page demo and would like to recreate this in my gantry template. I have module positions that allow full width however the main body for the component is limited to 1200px in my template. The only way I could achieve the same look as your demo would be to publish the issues in one of gantry's full width module positions which would require an issues module.

My other thought would be to redesign IMC3 to look more like the original IMC.

**Comment by itsam** [comment]
See also https://github.com/itsam/imc/issues/8
Issues as a module it's quite complicated but I think you can load any component in a module's position.

Moreover, the goal is to support multiple layouts so another layout (that you could select on menu or have the users select by themselves) could by the "original IMC" layout. For the latter I will a create very soon a branch so that anyone can test.
