### ISSUE TITLE
Map looks small.

### ISSUE THREAD

**Issue by asehir** [itsam/imc#17]
How can I resize it.

http://asehir.net/demo/

Thanks.

**Comment by itsam** [comment]
IMC3 comparing to the monolithic IMC for J2.5 is very modular so as to allow users to place the map, filter buttons and core component to any template position they like. That is achieved by breaking the component to modules and plugins. 

Now, concerning your case; Although you are using the same bootstrap based template as our demo, the results are different. That's because we have customized purity III to cover our needs (such as the fixed map). 

In the following link you can replace folder "local" to your template's path (smt like /var/www/joomla3/templates/purity_iii/local

https://www.dropbox.com/s/hcwl5idv05v80li/local.zip?dl=0

Then you should place module "Improve My City Google Map" to the position "sidebar-1".

Let us know if that helps.

**Comment by asehir** [comment]
I uploaded the folder and replaced with local but it did not work. Please let me know which layout you use.

Thanks.

**Comment by asehir** [comment]
I am trying to change css and I can make module bigger but map is always same :)

**Comment by itsam** [comment]
Make sure to select "Position & Responsive Configuration" the correct layout which is: imc-layout (local)

**Comment by asehir** [comment]
Yes I changed to imc-layout (local) and lost the filter also :) and map is a little bigger but not like it has to be.

*when I hide title of map it all disappears. title and the map also.

**Comment by asehir** [comment]
I think I need to choose cities theme instead of defaulti orange or red. I uploaded files but can not see the them.

**Comment by krogias** [comment]
Hi,
Yes to must choose the theme cities also.
In my case, I didn't replace the entire local folder with the zip provided
by Ioannis, but only the changed and new files of IMC.
That's how it worked for me:
1. "Save as a copy" for creating a new template for IMC
2. Theme: cities
3. Layout: imc-layout (local)
4. Sub layout: - use default- (local)
5. Don't forget to assign the template to your IMC menu


2015-09-03 20:32 GMT+03:00 asehir <notifications@github.com>:

**Comment by asehir** [comment]
I tried everything I dont know where I make the mistake. still same.

http://asehir.net/demo/tr/

**Comment by asehir** [comment]
Ok I just ad a min-height to gmap module css and it works fine now :)

Thanks

**Comment by gpalmas** [comment]
Hi.
I tried this hack and it works for me.
But with this layout there are no footer module positions. They are very useful to place some standard informations (as copyright, contact info, and other needed modules)...
