### ISSUE TITLE
Supervision Department

### ISSUE THREAD

**Issue by asehir** [itsam/imc#45]
How can I add Supervision Departments to the registration part.

Thanks.

**Comment by itsam** [comment]
Not sure what you mean. The registration part is not part of IMC.
Maybe you should check usergroups (from there the dropdown supervision department is populated)

**Comment by asehir** [comment]
![capture](https://cloud.githubusercontent.com/assets/14071009/19624825/0d0b33d2-9910-11e6-9597-0952e6dbf09c.png)
Please check the file. Supervision department is under Registration number on issues.

**Comment by itsam** [comment]
You need to create user groups (usually the root is the name of the municipality and the leaves the various municipality departments). Supervision Department just read the user groups (except the default Joomla ones) so that you can select which group is assigned to this issue. Then you need to assign your categories to user groups and of course users (officers) to user groups.
